### ISSUE TITLE
proto: full service message support

### ISSUE THREAD

**Issue by tdakkota** [gotd/td#163]
https://core.telegram.org/mtproto/service_messages

## ﻿Service Messages
- [ ] [Response to an RPC query](https://core.telegram.org/mtproto/service_messages#response-to-an-rpc-query)
- [ ] [RPC Error](https://core.telegram.org/mtproto/service_messages#rpc-error)
- [ ] [Cancellation of an RPC](https://core.telegram.org/mtproto/service_messages#cancellation-of-an-rpc-query)
- [ ] [Request for several future salts](https://core.telegram.org/mtproto/service_messages#request-for-several-future-salts)
- [ ] [Ping Messages (PING/PONG)](https://core.telegram.org/mtproto/service_messages#ping-messages-pingpong)
- [ ] [Deferred Connection Closure + PING](https://core.telegram.org/mtproto/service_messages#deferred-connection-closure--ping)
- [ ] [New Session Creation Notification](https://core.telegram.org/mtproto/service_messages#new-session-creation-notification)
- [ ] [Request to Destroy Session](https://core.telegram.org/mtproto/service_messages#request-to-destroy-session)

## Service Messages about Messages
- [ ] [Acknowledgment of Receipt](https://core.telegram.org/mtproto/service_messages_about_messages#acknowledgment-of-receipt)
- [ ] [Notice of Ignored Error Message](https://core.telegram.org/mtproto/service_messages_about_messages#notice-of-ignored-error-message)
- [ ] [Request for Message Status Information](https://core.telegram.org/mtproto/service_messages_about_messages#request-for-message-status-information)
- [ ] [Informational Message regarding Status of Messages](https://core.telegram.org/mtproto/service_messages_about_messages#informational-message-regarding-status-of-messages)
- [ ] [Voluntary Communication of Status of Messages](https://core.telegram.org/mtproto/service_messages_about_messages#voluntary-communication-of-status-of-messages)
- [ ] [Extended Voluntary Communication of Status of One Message](https://core.telegram.org/mtproto/service_messages_about_messages#extended-voluntary-communication-of-status-of-one-message)
- [ ] [Explicit Request to Re-Send Messages](https://core.telegram.org/mtproto/service_messages_about_messages#explicit-request-to-re-send-messages)
- [ ] [Explicit Request to Re-Send Answers](https://core.telegram.org/mtproto/service_messages_about_messages#explicit-request-to-re-send-answers)

## Containers
- [ ] [Simple Container](https://core.telegram.org/mtproto/service_messages#simple-container)
- [ ] [Message Copies](https://core.telegram.org/mtproto/service_messages#message-copies)
- [ ] [Packed Object](https://core.telegram.org/mtproto/service_messages#packed-object)

**Comment by ernado** [comment]
@stale не хулигань

**Comment by ernado** [comment]
Not really needed
