### ISSUE TITLE
client: add pretty Telethon-like common case functions

### ISSUE THREAD

**Issue by tdakkota** [gotd/td#28]
[Telethon client](https://docs.telethon.dev/en/latest/quick-references/client-reference.html) have some useful functions like [`iter_dialogs`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.dialogs.DialogMethods.iter_dialogs) or [`get_entity`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.users.UserMethods.get_entity).  It would be great to support similar functions in `gotd`. It can be stored in `tgflow` package or any another utility package.

TODO:

- [x] File downloads helpers
- [x] File uploads helpers
- [x] Updates state management (#91)
- [x] Pagination helpers (#145, implemented by #191)
- [x] Entity cache (#628)
- [x] `t.me` deeplinks and other resolve helpers
- [x] ~Sugared RPC calls builder (#146)~ (canceled)
