### ISSUE TITLE
client: implement updates handling

### ISSUE THREAD

**Issue by ernado** [gotd/td#91]
This is epic for client updates dispatching feature.

# Description
Client should provide exactly once (or at least once, TBD) guarantees for updates handling via dispatcher.

Also there should be (auto-generated) helpers that deal with Telegram entities, like [InputPeer](https://core.telegram.org/type/InputPeer)

# Reference
* [Working with updates](https://core.telegram.org/api/updates)
* [invokeWithoutUpdates](https://core.telegram.org/method/invokeWithoutUpdates)
* https://github.com/gotd/td/issues/28 (Helper functions)
* [channelDifferenceTooLong](https://core.telegram.org/constructor/updates.channelDifferenceTooLong) (handing situation when we should re-fetch state) 

# TODO

- [ ] Support all Update types (including short ones)
- [x] Support "fetch-only" connections (i.e. invokeWithoutUpdates)
- [x] Define interface for session storage
- [ ] Trigger state check on reconnect
- [ ] Trigger state check on long update absence (1 minute+? docs stayts 15min)
- [ ] TBD

# Handling state
1. For new state, generate pts=0(1?) and do not fetch difference, we want to process only new events starting for this moment
2. If fresh, get state and check for difference
3. If we detect gap, call getDifference (**or wait for ~0.5s**, incoming updates may fix the gap)
4. If we get [channelDifferenceTooLong](https://core.telegram.org/constructor/updates.channelDifferenceTooLong), we should act same as in (1)
    1. If we are bot, that means that all unprocessed messages for bot are lost at this moment
    2. If we are user, fetch latest history from chats

**Comment by ernado** [comment]
Just for record:

Bots should ignore unread_count that Telegram server receives. There is no way to use id and bot api server (that webhook-based default) does not change this value.

**Comment by ernado** [comment]
This was mostly implemented, thanks @xjem!
